### ISSUE TITLE
index unavaliable in Integer Model

### ISSUE THREAD

**Issue by petrSevostianov** [qmlweb/qmlweb#334] opened 2016-08-30 15:35 UTC
> http://doc.qt.io/qt-5/qtquick-modelviewsdata-modelview.html#integers-as-models
> it works in v0.1.0

```
import QtQuick 2.0
Column{
  spacing: 10
    Repeater{
      model:10
      delegate:Rectangle {
        anchors.left: parent.left
        anchors.right: parent.right
        height: 100
        color: "lightgray"

        Text {
          id: helloText
          text: index
          anchors.verticalCenter: parent.verticalCenter
          anchors.horizontalCenter: parent.horizontalCenter
          font.pointSize: 24; font.bold: true
        }
      }
    }  
}
```

**Comment by ChALkeR** [comment] 2016-09-02 19:14
@petrSevostianov Thanks for the report. Looks like a regression indeed.

**Comment by ChALkeR** [comment] 2016-09-09 16:37
Hm, it looks like it works for me.

@petrSevostianov, could you re-check this on current master?

**Comment by ChALkeR** [comment] 2016-12-12 11:25
Works for me in 0.2.0, in current master, and on qmlweb.github.io.

One nit: don't forget to set the `width` somewhere: either the root QML element should have `width` set or the DOM element that you are loading this to should have non-zero width.

Can't reproduce, closing. Feel free to leave comments if you can still reproduce this.

**Closed by ChALkeR** 2016-12-12 11:25 UTC
